[package]
name = "zk-nullifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crate = "0.0.2"
digest = "0.10.3"
ring = "0.16.20"
